spring:
  application:
    name: hw08new
  data:
    mongodb:
      host: localhost
      port: 27018
      database: book

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.hw08new.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
